use super::*;

pub(crate) fn config_entries_from(config: &TrailConfig) -> Vec<ConfigEntry> {
    vec![
        config_entry("workspace.id", &config.workspace.id.0, "string", true),
        config_entry(
            "workspace.default_branch",
            &config.workspace.default_branch,
            "string",
            false,
        ),
        config_entry("recording.mode", &config.recording.mode, "string", false),
        config_entry(
            "recording.debounce_ms",
            config.recording.debounce_ms,
            "u64",
            false,
        ),
        config_entry(
            "recording.ignore_gitignored",
            config.recording.ignore_gitignored,
            "bool",
            false,
        ),
        config_entry(
            "text.small_text_max_bytes",
            config.text.small_text_max_bytes,
            "u64",
            false,
        ),
        config_entry(
            "text.tree_text_min_bytes",
            config.text.tree_text_min_bytes,
            "u64",
            false,
        ),
        config_entry(
            "text.opaque_text_max_bytes",
            config.text.opaque_text_max_bytes,
            "u64",
            false,
        ),
        config_entry(
            "text.max_line_bytes",
            config.text.max_line_bytes,
            "u64",
            false,
        ),
        config_entry(
            "text.preserve_similarity",
            config.text.preserve_similarity,
            "f32",
            false,
        ),
        config_entry(
            "lane.default_materialize",
            config.lane.default_materialize,
            "bool",
            false,
        ),
        config_entry(
            "lane.require_test_gate",
            config.lane.require_test_gate,
            "bool",
            false,
        ),
        config_entry(
            "lane.require_eval_gate",
            config.lane.require_eval_gate,
            "bool",
            false,
        ),
        config_entry(
            "lane.required_test_suites",
            format_config_list(&config.lane.required_test_suites),
            "list",
            false,
        ),
        config_entry(
            "lane.required_eval_suites",
            format_config_list(&config.lane.required_eval_suites),
            "list",
            false,
        ),
        config_entry(
            "lane.claim_enforcement",
            &config.lane.claim_enforcement,
            "string",
            false,
        ),
        config_entry(
            "lane.enforce_sparse_paths",
            config.lane.enforce_sparse_paths,
            "bool",
            false,
        ),
        config_entry(
            "lane.max_patch_bytes",
            config.lane.max_patch_bytes,
            "u64",
            false,
        ),
        config_entry(
            "lane.max_patch_file_bytes",
            config.lane.max_patch_file_bytes,
            "u64",
            false,
        ),
        config_entry(
            "lane.max_changed_paths",
            config.lane.max_changed_paths,
            "u64",
            false,
        ),
        config_entry(
            "lane.max_event_payload_bytes",
            config.lane.max_event_payload_bytes,
            "u64",
            false,
        ),
        config_entry(
            "lane.max_trace_payload_bytes",
            config.lane.max_trace_payload_bytes,
            "u64",
            false,
        ),
        config_entry(
            "lane.worktrees_dir",
            &config.lane.worktrees_dir,
            "path",
            false,
        ),
        config_entry(
            "lane.merge_strategy",
            &config.lane.merge_strategy,
            "string",
            false,
        ),
        config_entry(
            "git.export_trailers",
            config.git.export_trailers,
            "bool",
            false,
        ),
        config_entry(
            "storage.prolly_backend",
            &config.storage.prolly_backend,
            "string",
            true,
        ),
        config_entry(
            "storage.slatedb_path",
            &config.storage.slatedb_path,
            "path",
            false,
        ),
        config_entry(
            "storage.slatedb_s3_endpoint",
            &config.storage.slatedb_s3_endpoint,
            "string",
            false,
        ),
        config_entry(
            "storage.slatedb_s3_bucket",
            &config.storage.slatedb_s3_bucket,
            "string",
            false,
        ),
        config_entry(
            "storage.slatedb_s3_region",
            &config.storage.slatedb_s3_region,
            "string",
            false,
        ),
        config_entry(
            "storage.slatedb_s3_access_key_id",
            &config.storage.slatedb_s3_access_key_id,
            "string",
            false,
        ),
        config_entry(
            "storage.slatedb_s3_secret_access_key",
            &config.storage.slatedb_s3_secret_access_key,
            "string",
            false,
        ),
        config_entry(
            "storage.slatedb_s3_allow_http",
            config.storage.slatedb_s3_allow_http,
            "bool",
            false,
        ),
        config_entry(
            "guardrails.policy",
            &config.guardrails.policy,
            "policy",
            false,
        ),
        config_entry(
            "workspace_views.upper_logical_bytes",
            config.workspace_views.upper_logical_bytes,
            "u64",
            false,
        ),
        config_entry(
            "workspace_views.upper_file_count",
            config.workspace_views.upper_file_count,
            "u64",
            false,
        ),
        config_entry(
            "workspace_views.single_file_bytes",
            config.workspace_views.single_file_bytes,
            "u64",
            false,
        ),
        config_entry(
            "workspace_views.journal_bytes",
            config.workspace_views.journal_bytes,
            "u64",
            false,
        ),
        config_entry(
            "workspace_views.cache_build_bytes",
            config.workspace_views.cache_build_bytes,
            "u64",
            false,
        ),
        config_entry(
            "workspace_views.concurrent_cache_builders",
            config.workspace_views.concurrent_cache_builders,
            "u64",
            false,
        ),
        config_entry(
            "workspace_views.cache_retention_secs",
            config.workspace_views.cache_retention_secs,
            "u64",
            false,
        ),
        config_entry(
            "workspace_views.cache_max_bytes",
            config.workspace_views.cache_max_bytes,
            "u64",
            false,
        ),
    ]
}

pub(crate) fn config_entry(
    key: impl Into<String>,
    value: impl ToString,
    value_type: impl Into<String>,
    read_only: bool,
) -> ConfigEntry {
    ConfigEntry {
        key: key.into(),
        value: value.to_string(),
        value_type: value_type.into(),
        read_only,
    }
}

pub(crate) fn format_config_list(values: &[String]) -> String {
    values.join(",")
}

pub(crate) fn config_entry_from(config: &TrailConfig, key: &str) -> Option<ConfigEntry> {
    config_entries_from(config)
        .into_iter()
        .find(|entry| entry.key == key)
}
