/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'index.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.android-arm64.node')
          } else {
            nativeBinding = require('@crabdb/prolly-node-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'index.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.android-arm-eabi.node')
          } else {
            nativeBinding = require('@crabdb/prolly-node-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'index.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@crabdb/prolly-node-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'index.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@crabdb/prolly-node-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'index.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@crabdb/prolly-node-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'index.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./index.darwin-universal.node')
      } else {
        nativeBinding = require('@crabdb/prolly-node-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'index.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.darwin-x64.node')
          } else {
            nativeBinding = require('@crabdb/prolly-node-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'index.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.darwin-arm64.node')
          } else {
            nativeBinding = require('@crabdb/prolly-node-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'index.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./index.freebsd-x64.node')
      } else {
        nativeBinding = require('@crabdb/prolly-node-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-x64-musl.node')
            } else {
              nativeBinding = require('@crabdb/prolly-node-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@crabdb/prolly-node-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@crabdb/prolly-node-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@crabdb/prolly-node-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@crabdb/prolly-node-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@crabdb/prolly-node-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@crabdb/prolly-node-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'index.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./index.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@crabdb/prolly-node-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'index.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./index.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@crabdb/prolly-node-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { NativeProllyBlobStore, NativeMergePolicyRegistry, NativeHostStore, NativeProllyEngine, cidFromBytes, nodeBytesRoundTrip, nodeCidFromBytes, verifyKeyProof, verifyMultiKeyProof, verifyRangeProof, verifyRangePageProof, verifyDiffPageProof, keyProofToBytes, keyProofFromBytes, multiKeyProofToBytes, multiKeyProofFromBytes, rangeProofToBytes, rangeProofFromBytes, rangePageProofToBytes, rangePageProofFromBytes, diffPageProofToBytes, diffPageProofFromBytes, inspectProofBundle, verifyProofBundle, signProofBundleHmacSha256, verifyAuthenticatedProofEnvelope, verifyAuthenticatedProofBundle, authenticatedProofEnvelopeToBytes, authenticatedProofEnvelopeFromBytes, keyProofFromNodeBytes, multiKeyProofFromNodeBytes, rangeProofFromNodeBytes, rangePageProofFromNodeBytes, isBoundaryConfigJson, prefixEnd, prefixRange, u64Key, u128Key, i64Key, i128Key, timestampMillisKey, encodeSegment, decodeSegments, debugKey, snapshotNamespaceBranch, snapshotNamespaceTag, snapshotNamespaceCheckpoint, snapshotNamespaceCustom, snapshotRootName, snapshotIdFromName, versionedValueBytesRoundTrip, valueRefBytesRoundTrip, rootManifestBytesRoundTrip, defaultLargeValueConfig, defaultParallelConfig, crdtConfigLww, crdtConfigMultiValue, timestampedValueToBytes, timestampedValueFromBytes, timestampedValueNow, multiValueSetToBytes, multiValueSetFromBytes, multiValueSetMerge, tombstoneToBytes, tombstoneFromBytes, tombstoneFromStoredBytes, isTombstoneValue, tombstoneUpsertMutation, tombstoneCompactionMutation } = nativeBinding

module.exports.NativeProllyBlobStore = NativeProllyBlobStore
module.exports.NativeMergePolicyRegistry = NativeMergePolicyRegistry
module.exports.NativeHostStore = NativeHostStore
module.exports.NativeProllyEngine = NativeProllyEngine
module.exports.cidFromBytes = cidFromBytes
module.exports.nodeBytesRoundTrip = nodeBytesRoundTrip
module.exports.nodeCidFromBytes = nodeCidFromBytes
module.exports.verifyKeyProof = verifyKeyProof
module.exports.verifyMultiKeyProof = verifyMultiKeyProof
module.exports.verifyRangeProof = verifyRangeProof
module.exports.verifyRangePageProof = verifyRangePageProof
module.exports.verifyDiffPageProof = verifyDiffPageProof
module.exports.keyProofToBytes = keyProofToBytes
module.exports.keyProofFromBytes = keyProofFromBytes
module.exports.multiKeyProofToBytes = multiKeyProofToBytes
module.exports.multiKeyProofFromBytes = multiKeyProofFromBytes
module.exports.rangeProofToBytes = rangeProofToBytes
module.exports.rangeProofFromBytes = rangeProofFromBytes
module.exports.rangePageProofToBytes = rangePageProofToBytes
module.exports.rangePageProofFromBytes = rangePageProofFromBytes
module.exports.diffPageProofToBytes = diffPageProofToBytes
module.exports.diffPageProofFromBytes = diffPageProofFromBytes
module.exports.inspectProofBundle = inspectProofBundle
module.exports.verifyProofBundle = verifyProofBundle
module.exports.signProofBundleHmacSha256 = signProofBundleHmacSha256
module.exports.verifyAuthenticatedProofEnvelope = verifyAuthenticatedProofEnvelope
module.exports.verifyAuthenticatedProofBundle = verifyAuthenticatedProofBundle
module.exports.authenticatedProofEnvelopeToBytes = authenticatedProofEnvelopeToBytes
module.exports.authenticatedProofEnvelopeFromBytes = authenticatedProofEnvelopeFromBytes
module.exports.keyProofFromNodeBytes = keyProofFromNodeBytes
module.exports.multiKeyProofFromNodeBytes = multiKeyProofFromNodeBytes
module.exports.rangeProofFromNodeBytes = rangeProofFromNodeBytes
module.exports.rangePageProofFromNodeBytes = rangePageProofFromNodeBytes
module.exports.isBoundaryConfigJson = isBoundaryConfigJson
module.exports.prefixEnd = prefixEnd
module.exports.prefixRange = prefixRange
module.exports.u64Key = u64Key
module.exports.u128Key = u128Key
module.exports.i64Key = i64Key
module.exports.i128Key = i128Key
module.exports.timestampMillisKey = timestampMillisKey
module.exports.encodeSegment = encodeSegment
module.exports.decodeSegments = decodeSegments
module.exports.debugKey = debugKey
module.exports.snapshotNamespaceBranch = snapshotNamespaceBranch
module.exports.snapshotNamespaceTag = snapshotNamespaceTag
module.exports.snapshotNamespaceCheckpoint = snapshotNamespaceCheckpoint
module.exports.snapshotNamespaceCustom = snapshotNamespaceCustom
module.exports.snapshotRootName = snapshotRootName
module.exports.snapshotIdFromName = snapshotIdFromName
module.exports.versionedValueBytesRoundTrip = versionedValueBytesRoundTrip
module.exports.valueRefBytesRoundTrip = valueRefBytesRoundTrip
module.exports.rootManifestBytesRoundTrip = rootManifestBytesRoundTrip
module.exports.defaultLargeValueConfig = defaultLargeValueConfig
module.exports.defaultParallelConfig = defaultParallelConfig
module.exports.crdtConfigLww = crdtConfigLww
module.exports.crdtConfigMultiValue = crdtConfigMultiValue
module.exports.timestampedValueToBytes = timestampedValueToBytes
module.exports.timestampedValueFromBytes = timestampedValueFromBytes
module.exports.timestampedValueNow = timestampedValueNow
module.exports.multiValueSetToBytes = multiValueSetToBytes
module.exports.multiValueSetFromBytes = multiValueSetFromBytes
module.exports.multiValueSetMerge = multiValueSetMerge
module.exports.tombstoneToBytes = tombstoneToBytes
module.exports.tombstoneFromBytes = tombstoneFromBytes
module.exports.tombstoneFromStoredBytes = tombstoneFromStoredBytes
module.exports.isTombstoneValue = isTombstoneValue
module.exports.tombstoneUpsertMutation = tombstoneUpsertMutation
module.exports.tombstoneCompactionMutation = tombstoneCompactionMutation
