/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface NodeTreeRecord {
  root?: Buffer
  config?: NodeConfigRecord
}
export interface NodeEntryRecord {
  key: Buffer
  value: Buffer
}
export interface NodeDiffRecord {
  kind: string
  key: Buffer
  value?: Buffer
  old?: Buffer
  newValue?: Buffer
}
export interface NodeMutationRecord {
  kind: string
  key: Buffer
  value?: Buffer
}
export interface NodeEncodingRecord {
  kind: string
  customName?: string
}
export interface NodeConfigRecord {
  minChunkSize: string
  maxChunkSize: string
  chunkingFactor: number
  hashSeed: string
  encoding: NodeEncodingRecord
  nodeCacheMaxNodes?: string
  nodeCacheMaxBytes?: string
}
export interface NodeParallelConfigRecord {
  maxThreads: string
  parallelismThreshold: string
}
export interface NodeSnapshotBundleNodeRecord {
  cid: Buffer
  bytes: Buffer
}
export interface NodeSnapshotBundleRecord {
  formatVersion: number
  tree: NodeTreeRecord
  nodes: Array<NodeSnapshotBundleNodeRecord>
}
export interface NodeSnapshotBundleSummaryRecord {
  formatVersion: number
  root?: Buffer
  nodeCount: string
  byteCount: string
  minNodeBytes: string
  maxNodeBytes: string
}
export interface NodeSnapshotBundleVerificationRecord {
  valid: boolean
  summary: NodeSnapshotBundleSummaryRecord
  reachableNodes: string
  reachableBytes: string
  missingCids: Array<Buffer>
  extraCids: Array<Buffer>
}
export interface NodeBatchApplyStatsRecord {
  inputMutations: string
  effectiveMutations: string
  preprocessInputSorted: boolean
  affectedLeaves: string
  changedLeaves: string
  sparseLeafApplies: string
  writtenNodes: string
  writtenBytes: string
  usedAppendFastPath: boolean
  usedBatchedRoute: boolean
  usedCoalescedRebuild: boolean
  usedDeferredRebalancing: boolean
  usedBottomUpRebuild: boolean
  cacheWrittenNodes: boolean
}
export interface NodeBatchApplyResultRecord {
  tree: NodeTreeRecord
  stats: NodeBatchApplyStatsRecord
}
export interface NodeHostStoreEmptyRequest {
  
}
export interface NodeHostStoreKeyRequest {
  key: Buffer
}
export interface NodeHostStorePutRequest {
  key: Buffer
  value: Buffer
}
export interface NodeHostStoreBatchRequest {
  ops: Array<NodeMutationRecord>
}
export interface NodeHostStoreBatchGetRequest {
  keys: Array<Buffer>
}
export interface NodeHostStoreHintRequest {
  namespace: Buffer
  key: Buffer
}
export interface NodeHostStorePutHintRequest {
  namespace: Buffer
  key: Buffer
  value: Buffer
}
export interface NodeHostStoreRootRequest {
  name: Buffer
}
export interface NodeHostStorePutRootRequest {
  name: Buffer
  manifest: Buffer
}
export interface NodeHostStoreCasRootRequest {
  name: Buffer
  expected?: Buffer
  replacement?: Buffer
}
export interface NodeHostStoreBytesResult {
  value?: Buffer
  ok: boolean
  error?: string
}
export interface NodeHostStoreUnitResult {
  error?: string
}
export interface NodeHostStoreBoolResult {
  value: boolean
  error?: string
}
export interface NodeHostStoreBatchGetResult {
  values: Array<NodeHostStoreBytesResult>
  error?: string
}
export interface NodeHostStoreListBytesResult {
  values: Array<Buffer>
  error?: string
}
export interface NodeHostStoreRootResult {
  value?: Buffer
  error?: string
}
export interface NodeHostStoreNamedRootManifest {
  name: Buffer
  manifest: Buffer
}
export interface NodeHostStoreListRootsResult {
  values: Array<NodeHostStoreNamedRootManifest>
  error?: string
}
export interface NodeHostStoreCasResult {
  applied: boolean
  current?: Buffer
  error?: string
}
export interface NodeRangeCursorRecord {
  afterKey?: Buffer
}
export interface NodeReverseCursorRecord {
  beforeKey?: Buffer
}
export interface NodeRangeBoundsRecord {
  start: Buffer
  end?: Buffer
}
export interface NodeRangePageRecord {
  entries: Array<NodeEntryRecord>
  nextCursor?: NodeRangeCursorRecord
}
export interface NodeReversePageRecord {
  entries: Array<NodeEntryRecord>
  nextCursor?: NodeReverseCursorRecord
}
export interface NodeCursorWindowRecord {
  positionKey?: Buffer
  positionValue?: Buffer
  found: boolean
  entries: Array<NodeEntryRecord>
  nextCursor?: NodeRangeCursorRecord
}
export interface NodeDiffPageRecord {
  diffs: Array<NodeDiffRecord>
  nextCursor?: NodeRangeCursorRecord
}
export interface NodeConflictRecord {
  key: Buffer
  base?: Buffer
  left?: Buffer
  right?: Buffer
}
export interface NodeResolutionRecord {
  kind: string
  value?: Buffer
}
export interface NodeCrdtResolutionRecord {
  kind: string
  value?: Buffer
}
export interface NodeConflictPageRecord {
  conflicts: Array<NodeConflictRecord>
  nextCursor?: NodeRangeCursorRecord
}
export interface NodeDiffTraversalStatsRecord {
  comparedNodes: string
  reusedSubtrees: string
  addedSubtrees: string
  removedSubtrees: string
  collectedFallbacks: string
  emittedDiffs: string
}
export interface NodeStructuralDiffPageRecord {
  diffs: Array<NodeDiffRecord>
  nextCursorJson?: string
  stats: NodeDiffTraversalStatsRecord
  nextCursor?: NodeStructuralDiffCursorRecord
}
export interface NodeStructuralDiffCursorRecord {
  baseRoot?: Buffer
  otherRoot?: Buffer
  markers: Array<NodeStructuralDiffMarkerRecord>
  pending: Array<NodeDiffRecord>
}
export interface NodeStructuralDiffMarkerRecord {
  kind: string
  baseCid?: Buffer
  otherCid?: Buffer
  spanEnd?: Buffer
  cid?: Buffer
}
export interface NodeMergeTraceRecord {
  events: Array<NodeMergeTraceEventRecord>
}
export interface NodeMergeTraceEventRecord {
  kind: string
  fastPath?: string
  cid?: Buffer
  reuseReason?: string
  level?: string
  entries?: string
  firstKey?: Buffer
  lastKey?: Buffer
  stage?: string
  key?: Buffer
  resolution?: string
  fallbackReason?: string
  diffStats?: NodeDiffTraversalStatsRecord
  rightChanges?: string
  mutations?: string
  appendOnly?: boolean
}
export interface NodeMergeExplanationRecord {
  result?: NodeTreeRecord
  error?: string
  traceJson: string
  trace: NodeMergeTraceRecord
}
export interface NodeNamedRootRecord {
  name: Buffer
  tree: NodeTreeRecord
}
export interface NodeRootManifestRecord {
  tree: NodeTreeRecord
  createdAtMillis?: string
  updatedAtMillis?: string
}
export interface NodeNamedRootManifestRecord {
  name: Buffer
  manifest: NodeRootManifestRecord
}
export interface NodeNamedRootSelectionRecord {
  roots: Array<NodeNamedRootRecord>
  missingNames: Array<Buffer>
}
export interface NodeNamedRootUpdateRecord {
  applied: boolean
  conflict: boolean
  current?: NodeTreeRecord
}
export interface NodeSnapshotNamespaceRecord {
  kind: string
  customPrefix?: Buffer
}
export interface NodeSnapshotRecord {
  id: Buffer
  name: Buffer
  tree: NodeTreeRecord
  createdAtMillis?: string
  updatedAtMillis?: string
}
export interface NodeSnapshotSelectionRecord {
  snapshots: Array<NodeSnapshotRecord>
  missingIds: Array<Buffer>
}
export interface NodeKeyProofRecord {
  root?: Buffer
  key: Buffer
  pathNodeBytes: Array<Buffer>
}
export interface NodeKeyProofVerificationRecord {
  valid: boolean
  exists: boolean
  absence: boolean
  root?: Buffer
  key: Buffer
  value?: Buffer
}
export interface NodeMultiKeyProofRecord {
  root?: Buffer
  keys: Array<Buffer>
  pathNodeBytes: Array<Buffer>
}
export interface NodeMultiKeyProofVerificationRecord {
  valid: boolean
  root?: Buffer
  results: Array<NodeKeyProofVerificationRecord>
}
export interface NodeRangeProofRecord {
  root?: Buffer
  start: Buffer
  end?: Buffer
  pathNodeBytes: Array<Buffer>
}
export interface NodeRangeProofVerificationRecord {
  valid: boolean
  root?: Buffer
  start: Buffer
  end?: Buffer
  entries: Array<NodeEntryRecord>
}
export interface NodeRangePageProofRecord {
  root?: Buffer
  after?: Buffer
  end?: Buffer
  pathNodeBytes: Array<Buffer>
}
export interface NodeRangePageProofVerificationRecord {
  valid: boolean
  root?: Buffer
  after?: Buffer
  end?: Buffer
  entries: Array<NodeEntryRecord>
}
export interface NodeProvedRangePageRecord {
  page: NodeRangePageRecord
  proof: NodeRangePageProofRecord
}
export interface NodeDiffPageProofRecord {
  base: NodeRangePageProofRecord
  other: NodeRangePageProofRecord
  lookaheadBase?: NodeKeyProofRecord
  lookaheadOther?: NodeKeyProofRecord
  requestedEnd?: Buffer
  limit: string
}
export interface NodeDiffPageProofVerificationRecord {
  valid: boolean
  baseValid: boolean
  otherValid: boolean
  lookaheadValid: boolean
  baseRoot?: Buffer
  otherRoot?: Buffer
  after?: Buffer
  requestedEnd?: Buffer
  proofEnd?: Buffer
  limit: string
  diffs: Array<NodeDiffRecord>
  nextCursor?: NodeRangeCursorRecord
}
export interface NodeProvedDiffPageRecord {
  page: NodeDiffPageRecord
  proof: NodeDiffPageProofRecord
}
export interface NodeProofBundleSummaryRecord {
  version: string
  kind: string
  root?: Buffer
  otherRoot?: Buffer
  keyCount: string
  pathNodeCount: string
  start?: Buffer
  end?: Buffer
  after?: Buffer
  requestedEnd?: Buffer
  limit?: string
  hasLookahead: boolean
}
export interface NodeProofBundleVerificationRecord {
  summary: NodeProofBundleSummaryRecord
  valid: boolean
  existsCount: string
  absenceCount: string
  entryCount: string
  diffCount: string
  nextCursor?: NodeRangeCursorRecord
}
export interface NodeAuthenticatedProofEnvelopeRecord {
  algorithm: string
  keyId: Buffer
  proofBundle: Buffer
  context: Buffer
  issuedAtMillis?: string
  expiresAtMillis?: string
  nonce: Buffer
  signature: Buffer
}
export interface NodeAuthenticatedProofEnvelopeVerificationRecord {
  valid: boolean
  signatureValid: boolean
  timeValid: boolean
  notYetValid: boolean
  expired: boolean
  algorithm: string
  keyId: Buffer
  proofBundle: Buffer
  context: Buffer
  issuedAtMillis?: string
  expiresAtMillis?: string
  nonce: Buffer
}
export interface NodeAuthenticatedProofBundleVerificationRecord {
  valid: boolean
  envelope: NodeAuthenticatedProofEnvelopeVerificationRecord
  proof?: NodeProofBundleVerificationRecord
  proofError?: string
}
export interface NodeNamedRootRetentionRecord {
  kind: string
  names: Array<Buffer>
  prefix?: Buffer
  count?: string
  minUpdatedAtMillis?: string
}
export interface NodeCacheStatsRecord {
  cachedNodes: string
  cachedBytes: string
  pinnedNodes: string
  pinnedBytes: string
}
export interface NodeMetricsRecord {
  nodeCacheHits: string
  nodeCacheMisses: string
  nodeCacheEvictions: string
  nodesRead: string
  bytesRead: string
  nodesWritten: string
  bytesWritten: string
  storeGetCalls: string
  storeBatchGetCalls: string
  storeBatchGetKeys: string
  storePutCalls: string
  storeBatchPutCalls: string
  storeBatchPutNodes: string
}
export interface NodeChangedSpanRecord {
  start: Buffer
  end?: Buffer
}
export interface NodeChangedSpanHintRecord {
  baseRoot?: Buffer
  changedRoot?: Buffer
  spans: Array<NodeChangedSpanRecord>
}
export interface NodeGcReachabilityRecord {
  liveCids: Array<Buffer>
  liveNodes: string
  liveBytes: string
  leafNodes: string
  internalNodes: string
}
export interface NodeGcPlanRecord {
  reachability: NodeGcReachabilityRecord
  candidateNodes: string
  reclaimableCids: Array<Buffer>
  reclaimableNodes: string
  reclaimableBytes: string
  missingCandidates: string
}
export interface NodeGcSweepRecord {
  plan: NodeGcPlanRecord
  deletedNodes: string
  deletedBytes: string
}
export interface NodeMissingNodePlanRecord {
  requiredCids: Array<Buffer>
  requiredNodes: string
  requiredBytes: string
  missingCids: Array<Buffer>
  missingNodes: string
  missingBytes: string
}
export interface NodeMissingNodeCopyRecord {
  plan: NodeMissingNodePlanRecord
  copiedNodes: string
  copiedBytes: string
}
export interface NodeBlobRefRecord {
  cid: Buffer
  len: string
}
export interface NodeLargeValueConfigRecord {
  inlineThreshold: string
}
export interface NodeValueRefRecord {
  kind: string
  value?: Buffer
  blob?: NodeBlobRefRecord
}
export interface NodeBlobGcReachabilityRecord {
  liveBlobs: Array<NodeBlobRefRecord>
  liveBlobCount: string
  liveBlobBytes: string
  scannedNodes: string
  scannedValues: string
}
export interface NodeBlobGcPlanRecord {
  reachability: NodeBlobGcReachabilityRecord
  candidateBlobs: string
  reclaimableBlobs: Array<NodeBlobRefRecord>
  reclaimableBlobCount: string
  reclaimableBlobBytes: string
  missingCandidates: string
}
export interface NodeBlobGcSweepRecord {
  plan: NodeBlobGcPlanRecord
  deletedBlobs: string
  deletedBlobBytes: string
}
export interface NodeCrdtConfigRecord {
  strategy: string
  deletePolicy: string
}
export interface NodeTimestampedValueRecord {
  value: Buffer
  timestamp: string
}
export interface NodeTombstoneMetadataRecord {
  key: string
  value: Buffer
}
export interface NodeTombstoneRecord {
  actor: Buffer
  timestampMillis: string
  causalMetadata: Array<NodeTombstoneMetadataRecord>
}
export declare function cidFromBytes(bytes: Buffer): Buffer
export declare function nodeBytesRoundTrip(bytes: Buffer): Buffer
export declare function nodeCidFromBytes(bytes: Buffer): Buffer
export declare function verifyKeyProof(proof: NodeKeyProofRecord): NodeKeyProofVerificationRecord
export declare function verifyMultiKeyProof(proof: NodeMultiKeyProofRecord): NodeMultiKeyProofVerificationRecord
export declare function verifyRangeProof(proof: NodeRangeProofRecord): NodeRangeProofVerificationRecord
export declare function verifyRangePageProof(proof: NodeRangePageProofRecord): NodeRangePageProofVerificationRecord
export declare function verifyDiffPageProof(proof: NodeDiffPageProofRecord): NodeDiffPageProofVerificationRecord
export declare function keyProofToBytes(proof: NodeKeyProofRecord): Buffer
export declare function keyProofFromBytes(bytes: Buffer): NodeKeyProofRecord
export declare function multiKeyProofToBytes(proof: NodeMultiKeyProofRecord): Buffer
export declare function multiKeyProofFromBytes(bytes: Buffer): NodeMultiKeyProofRecord
export declare function rangeProofToBytes(proof: NodeRangeProofRecord): Buffer
export declare function rangeProofFromBytes(bytes: Buffer): NodeRangeProofRecord
export declare function rangePageProofToBytes(proof: NodeRangePageProofRecord): Buffer
export declare function rangePageProofFromBytes(bytes: Buffer): NodeRangePageProofRecord
export declare function diffPageProofToBytes(proof: NodeDiffPageProofRecord): Buffer
export declare function diffPageProofFromBytes(bytes: Buffer): NodeDiffPageProofRecord
export declare function inspectProofBundle(bytes: Buffer): NodeProofBundleSummaryRecord
export declare function verifyProofBundle(bytes: Buffer): NodeProofBundleVerificationRecord
export declare function signProofBundleHmacSha256(proofBundle: Buffer, keyId: Buffer, secret: Buffer, context: Buffer, issuedAtMillis: string | undefined | null, expiresAtMillis: string | undefined | null, nonce: Buffer): NodeAuthenticatedProofEnvelopeRecord
export declare function verifyAuthenticatedProofEnvelope(envelope: NodeAuthenticatedProofEnvelopeRecord, secret: Buffer, nowMillis?: string | undefined | null): NodeAuthenticatedProofEnvelopeVerificationRecord
export declare function verifyAuthenticatedProofBundle(envelopeBytes: Buffer, secret: Buffer, nowMillis?: string | undefined | null): NodeAuthenticatedProofBundleVerificationRecord
export declare function authenticatedProofEnvelopeToBytes(envelope: NodeAuthenticatedProofEnvelopeRecord): Buffer
export declare function authenticatedProofEnvelopeFromBytes(bytes: Buffer): NodeAuthenticatedProofEnvelopeRecord
export declare function keyProofFromNodeBytes(root: Buffer | undefined | null, key: Buffer, pathNodeBytes: Array<Buffer>): NodeKeyProofRecord
export declare function multiKeyProofFromNodeBytes(root: Buffer | undefined | null, keys: Array<Buffer>, pathNodeBytes: Array<Buffer>): NodeMultiKeyProofRecord
export declare function rangeProofFromNodeBytes(root: Buffer | undefined | null, start: Buffer, end: Buffer | undefined | null, pathNodeBytes: Array<Buffer>): NodeRangeProofRecord
export declare function rangePageProofFromNodeBytes(root: Buffer | undefined | null, after: Buffer | undefined | null, end: Buffer | undefined | null, pathNodeBytes: Array<Buffer>): NodeRangePageProofRecord
export declare function isBoundaryConfigJson(configJson: string, count: string, key: Buffer, value: Buffer): boolean
export declare function prefixEnd(prefix: Buffer): Buffer | null
export declare function prefixRange(prefix: Buffer): NodeRangeBoundsRecord
export declare function rangeCursorStart(): NodeRangeCursorRecord
export declare function rangeCursorAfterKey(key: Buffer): NodeRangeCursorRecord
export declare function reverseCursorEnd(): NodeReverseCursorRecord
export declare function reverseCursorBeforeKey(key: Buffer): NodeReverseCursorRecord
export declare function upsertMutation(key: Buffer, value: Buffer): NodeMutationRecord
export declare function deleteMutation(key: Buffer): NodeMutationRecord
export declare function resolutionValue(value: Buffer): NodeResolutionRecord
export declare function resolutionDelete(): NodeResolutionRecord
export declare function resolutionUnresolved(): NodeResolutionRecord
export declare function resolvePreferLeft(conflict: NodeConflictRecord): NodeResolutionRecord
export declare function resolvePreferRight(conflict: NodeConflictRecord): NodeResolutionRecord
export declare function resolveDeleteWins(conflict: NodeConflictRecord): NodeResolutionRecord
export declare function resolveUpdateWins(conflict: NodeConflictRecord): NodeResolutionRecord
export declare function crdtResolutionValue(value: Buffer): NodeCrdtResolutionRecord
export declare function crdtResolutionDelete(): NodeCrdtResolutionRecord
export declare function u64Key(value: string): Buffer
export declare function u128Key(value: string): Buffer
export declare function i64Key(value: string): Buffer
export declare function i128Key(value: string): Buffer
export declare function timestampMillisKey(value: string): Buffer
export declare function encodeSegment(segment: Buffer): Buffer
export declare function keyFromSegments(segments: Array<Buffer>): Buffer
export declare function keyFromPrefixedSegments(prefix: Buffer, segments: Array<Buffer>): Buffer
export declare function changedSpan(start: Buffer, end?: Buffer | undefined | null): NodeChangedSpanRecord
export declare function changedSpanFromKey(key: Buffer): NodeChangedSpanRecord
export declare function changedSpanForPrefix(prefix: Buffer): NodeChangedSpanRecord
export declare function retainAllNamedRoots(): NodeNamedRootRetentionRecord
export declare function retainExactNamedRoots(names: Array<Buffer>): NodeNamedRootRetentionRecord
export declare function retainNamedRootPrefix(prefix: Buffer): NodeNamedRootRetentionRecord
export declare function retainNewestNamedRoots(prefix: Buffer, count: string): NodeNamedRootRetentionRecord
export declare function retainNamedRootsUpdatedSince(prefix: Buffer, minUpdatedAtMillis: string): NodeNamedRootRetentionRecord
export declare function decodeSegments(key: Buffer): Array<Buffer>
export declare function debugKey(key: Buffer): string
export declare function snapshotNamespaceBranch(): NodeSnapshotNamespaceRecord
export declare function snapshotNamespaceTag(): NodeSnapshotNamespaceRecord
export declare function snapshotNamespaceCheckpoint(): NodeSnapshotNamespaceRecord
export declare function snapshotNamespaceCustom(prefix: Buffer): NodeSnapshotNamespaceRecord
export declare function snapshotRootName(namespace: NodeSnapshotNamespaceRecord, id: Buffer): Buffer
export declare function snapshotIdFromName(namespace: NodeSnapshotNamespaceRecord, name: Buffer): Buffer | null
export declare function versionedValueBytesRoundTrip(bytes: Buffer): Buffer
export declare function versionedValueBytesMatchesSchema(bytes: Buffer, schema: string, version: string): boolean
export declare function versionedValueBytesRequireSchema(bytes: Buffer, schema: string, version: string): void
export declare function valueRefBytesRoundTrip(bytes: Buffer): Buffer
export declare function valueRefFromStoredBytes(bytes: Buffer): NodeValueRefRecord
export declare function valueRefInlineRequiresEscape(value: Buffer): boolean
export declare function blobRefValidateBytes(reference: NodeBlobRefRecord, bytes: Buffer): void
export declare function rootManifestBytesRoundTrip(bytes: Buffer): Buffer
export declare function snapshotBundleToBytes(bundle: NodeSnapshotBundleRecord): Buffer
export declare function snapshotBundleFromBytes(bytes: Buffer): NodeSnapshotBundleRecord
export declare function snapshotBundleDigest(bundle: NodeSnapshotBundleRecord): Buffer
export declare function snapshotBundleDigestBytes(bytes: Buffer): Buffer
export declare function snapshotBundleSummary(bundle: NodeSnapshotBundleRecord): NodeSnapshotBundleSummaryRecord
export declare function snapshotBundleSummaryFromBytes(bytes: Buffer): NodeSnapshotBundleSummaryRecord
export declare function verifySnapshotBundle(bundle: NodeSnapshotBundleRecord): NodeSnapshotBundleVerificationRecord
export declare function verifySnapshotBundleBytes(bytes: Buffer): NodeSnapshotBundleVerificationRecord
export declare function defaultConfig(): NodeConfigRecord
export declare function encodingRaw(): NodeEncodingRecord
export declare function encodingCbor(): NodeEncodingRecord
export declare function encodingJson(): NodeEncodingRecord
export declare function encodingCustom(name: string): NodeEncodingRecord
export declare function treeConfig(minChunkSize: string, maxChunkSize: string, chunkingFactor: number, hashSeed: string, encoding: NodeEncodingRecord, nodeCacheMaxNodes?: string | undefined | null, nodeCacheMaxBytes?: string | undefined | null): NodeConfigRecord
export declare function defaultLargeValueConfig(): NodeLargeValueConfigRecord
export declare function largeValueConfig(inlineThreshold: string): NodeLargeValueConfigRecord
export declare function defaultParallelConfig(): NodeParallelConfigRecord
export declare function parallelConfig(maxThreads: string, parallelismThreshold: string): NodeParallelConfigRecord
export declare function parallelConfigSequential(): NodeParallelConfigRecord
export declare function crdtConfigLww(deletePolicy: string): NodeCrdtConfigRecord
export declare function crdtConfigMultiValue(deletePolicy: string): NodeCrdtConfigRecord
export declare function timestampedValueToBytes(record: NodeTimestampedValueRecord): Buffer
export declare function timestampedValueFromBytes(bytes: Buffer): NodeTimestampedValueRecord
export declare function timestampedValueNow(value: Buffer): NodeTimestampedValueRecord
export declare function multiValueSetToBytes(values: Array<Buffer>): Buffer
export declare function multiValueSetFromBytes(bytes: Buffer): Array<Buffer>
export declare function multiValueSetMerge(left: Array<Buffer>, right: Array<Buffer>): Array<Buffer>
export declare function tombstoneToBytes(record: NodeTombstoneRecord): Buffer
export declare function tombstoneFromBytes(bytes: Buffer): NodeTombstoneRecord
export declare function tombstoneFromStoredBytes(bytes: Buffer): NodeTombstoneRecord | null
export declare function isTombstoneValue(bytes: Buffer): boolean
export declare function tombstoneUpsertMutation(key: Buffer, tombstone: NodeTombstoneRecord): NodeMutationRecord
export declare function tombstoneCompactionMutation(key: Buffer, storedValue: Buffer): NodeMutationRecord | null
export declare class NativeProllyBlobStore {
  static memory(): NativeProllyBlobStore
  static file(path: string): NativeProllyBlobStore
  putBlob(bytes: Buffer): NodeBlobRefRecord
  getBlob(reference: NodeBlobRefRecord): Buffer | null
  deleteBlob(reference: NodeBlobRefRecord): void
  listBlobRefs(): Array<NodeBlobRefRecord>
  blobCount(): string
}
export declare class NativeMergePolicyRegistry {
  constructor()
  len(): string
  isEmpty(): boolean
  hasDefault(): boolean
  setDefaultResolverName(name: string): void
  setDefaultResolver(resolver: (conflict: NodeConflictRecord) => NodeResolutionRecord): void
  pushPrefixResolverName(prefix: Buffer, name: string): void
  pushPrefixResolver(prefix: Buffer, resolver: (conflict: NodeConflictRecord) => NodeResolutionRecord): void
  pushExactResolverName(key: Buffer, name: string): void
  pushExactResolver(key: Buffer, resolver: (conflict: NodeConflictRecord) => NodeResolutionRecord): void
}
export declare class NativeHostStore {
  constructor(get: (arg: NodeHostStoreKeyRequest) => NodeHostStoreBytesResult, put: (arg: NodeHostStorePutRequest) => NodeHostStoreUnitResult, delete: (arg: NodeHostStoreKeyRequest) => NodeHostStoreUnitResult, batch: (arg: NodeHostStoreBatchRequest) => NodeHostStoreUnitResult, batchGetOrdered: (arg: NodeHostStoreBatchGetRequest) => NodeHostStoreBatchGetResult, prefersBatchReads: (arg: NodeHostStoreEmptyRequest) => NodeHostStoreBoolResult, supportsHints: (arg: NodeHostStoreEmptyRequest) => NodeHostStoreBoolResult, getHint: (arg: NodeHostStoreHintRequest) => NodeHostStoreBytesResult, putHint: (arg: NodeHostStorePutHintRequest) => NodeHostStoreUnitResult, listNodeCids: (arg: NodeHostStoreEmptyRequest) => NodeHostStoreListBytesResult, getRoot: (arg: NodeHostStoreRootRequest) => NodeHostStoreRootResult, putRoot: (arg: NodeHostStorePutRootRequest) => NodeHostStoreUnitResult, deleteRoot: (arg: NodeHostStoreRootRequest) => NodeHostStoreUnitResult, compareAndSwapRoot: (arg: NodeHostStoreCasRootRequest) => NodeHostStoreCasResult, listRoots: (arg: NodeHostStoreEmptyRequest) => NodeHostStoreListRootsResult)
}
export declare class NativeProllyEngine {
  static memory(): NativeProllyEngine
  static memoryWithConfigJson(configJson: string): NativeProllyEngine
  static customStore(store: NativeHostStore): NativeProllyEngine
  static customStoreWithConfigJson(store: NativeHostStore, configJson: string): NativeProllyEngine
  static file(path: string): NativeProllyEngine
  static fileWithConfigJson(path: string, configJson: string): NativeProllyEngine
  static sqlite(path: string): NativeProllyEngine
  static sqliteWithConfigJson(path: string, configJson: string): NativeProllyEngine
  static sqliteInMemory(): NativeProllyEngine
  static sqliteInMemoryWithConfigJson(configJson: string): NativeProllyEngine
  create(): NodeTreeRecord
  put(tree: NodeTreeRecord, key: Buffer, value: Buffer): NodeTreeRecord
  delete(tree: NodeTreeRecord, key: Buffer): NodeTreeRecord
  get(tree: NodeTreeRecord, key: Buffer): Buffer | null
  getValueRef(tree: NodeTreeRecord, key: Buffer): NodeValueRefRecord | null
  getLargeValue(blobStore: NativeProllyBlobStore, tree: NodeTreeRecord, key: Buffer): Buffer | null
  putLargeValue(blobStore: NativeProllyBlobStore, tree: NodeTreeRecord, key: Buffer, value: Buffer, config: NodeLargeValueConfigRecord): NodeTreeRecord
  getMany(tree: NodeTreeRecord, keys: Array<Buffer>): Array<Buffer | undefined | null>
  proveKey(tree: NodeTreeRecord, key: Buffer): NodeKeyProofRecord
  proveKeys(tree: NodeTreeRecord, keys: Array<Buffer>): NodeMultiKeyProofRecord
  proveRange(tree: NodeTreeRecord, start: Buffer, end?: Buffer | undefined | null): NodeRangeProofRecord
  provePrefix(tree: NodeTreeRecord, prefix: Buffer): NodeRangeProofRecord
  proveRangePage(tree: NodeTreeRecord, cursor: NodeRangeCursorRecord | undefined | null, end: Buffer | undefined | null, limit: string): NodeProvedRangePageRecord
  proveDiffPage(base: NodeTreeRecord, other: NodeTreeRecord, cursor: NodeRangeCursorRecord | undefined | null, end: Buffer | undefined | null, limit: string): NodeProvedDiffPageRecord
  batch(tree: NodeTreeRecord, mutations: Array<NodeMutationRecord>): NodeTreeRecord
  batchWithStats(tree: NodeTreeRecord, mutations: Array<NodeMutationRecord>): NodeBatchApplyResultRecord
  parallelBatch(tree: NodeTreeRecord, mutations: Array<NodeMutationRecord>, config: NodeParallelConfigRecord): NodeTreeRecord
  parallelBatchWithStats(tree: NodeTreeRecord, mutations: Array<NodeMutationRecord>, config: NodeParallelConfigRecord): NodeBatchApplyResultRecord
  buildFromEntries(entries: Array<NodeEntryRecord>): NodeTreeRecord
  buildFromSortedEntries(entries: Array<NodeEntryRecord>): NodeTreeRecord
  appendBatch(tree: NodeTreeRecord, mutations: Array<NodeMutationRecord>): NodeTreeRecord
  appendBatchWithStats(tree: NodeTreeRecord, mutations: Array<NodeMutationRecord>): NodeBatchApplyResultRecord
  firstEntry(tree: NodeTreeRecord): NodeEntryRecord | null
  lastEntry(tree: NodeTreeRecord): NodeEntryRecord | null
  lowerBound(tree: NodeTreeRecord, key: Buffer): NodeEntryRecord | null
  upperBound(tree: NodeTreeRecord, key: Buffer): NodeEntryRecord | null
  range(tree: NodeTreeRecord, start: Buffer, end?: Buffer | undefined | null): Array<NodeEntryRecord>
  prefix(tree: NodeTreeRecord, prefix: Buffer): Array<NodeEntryRecord>
  prefixPage(tree: NodeTreeRecord, prefix: Buffer, cursor: NodeRangeCursorRecord | undefined | null, limit: string): NodeRangePageRecord
  prefixReversePage(tree: NodeTreeRecord, prefix: Buffer, cursor: NodeReverseCursorRecord | undefined | null, limit: string): NodeReversePageRecord
  rangeAfter(tree: NodeTreeRecord, afterKey: Buffer, end?: Buffer | undefined | null): Array<NodeEntryRecord>
  rangeFromCursor(tree: NodeTreeRecord, cursor?: NodeRangeCursorRecord | undefined | null, end?: Buffer | undefined | null): Array<NodeEntryRecord>
  rangePage(tree: NodeTreeRecord, cursor: NodeRangeCursorRecord | undefined | null, end: Buffer | undefined | null, limit: string): NodeRangePageRecord
  reversePage(tree: NodeTreeRecord, cursor: NodeReverseCursorRecord | undefined | null, start: Buffer, limit: string): NodeReversePageRecord
  cursorWindow(tree: NodeTreeRecord, key: Buffer, end: Buffer | undefined | null, limit: string): NodeCursorWindowRecord
  diff(base: NodeTreeRecord, other: NodeTreeRecord): Array<NodeDiffRecord>
  rangeDiff(base: NodeTreeRecord, other: NodeTreeRecord, start: Buffer, end?: Buffer | undefined | null): Array<NodeDiffRecord>
  diffFromCursor(base: NodeTreeRecord, other: NodeTreeRecord, cursor?: NodeRangeCursorRecord | undefined | null, end?: Buffer | undefined | null): Array<NodeDiffRecord>
  diffPage(base: NodeTreeRecord, other: NodeTreeRecord, cursor: NodeRangeCursorRecord | undefined | null, end: Buffer | undefined | null, limit: string): NodeDiffPageRecord
  conflictPage(base: NodeTreeRecord, left: NodeTreeRecord, right: NodeTreeRecord, cursor: NodeRangeCursorRecord | undefined | null, limit: string): NodeConflictPageRecord
  merge(base: NodeTreeRecord, left: NodeTreeRecord, right: NodeTreeRecord, resolver?: string | undefined | null): NodeTreeRecord
  mergeWithResolver(base: NodeTreeRecord, left: NodeTreeRecord, right: NodeTreeRecord, resolver: (conflict: NodeConflictRecord) => NodeResolutionRecord): NodeTreeRecord
  mergeWithPolicy(base: NodeTreeRecord, left: NodeTreeRecord, right: NodeTreeRecord, policy: NativeMergePolicyRegistry): NodeTreeRecord
  crdtMerge(base: NodeTreeRecord, left: NodeTreeRecord, right: NodeTreeRecord, config: NodeCrdtConfigRecord): NodeTreeRecord
  crdtMergeWithResolver(base: NodeTreeRecord, left: NodeTreeRecord, right: NodeTreeRecord, deletePolicy: string, resolver: (conflict: NodeConflictRecord) => NodeCrdtResolutionRecord): NodeTreeRecord
  mergeExplain(base: NodeTreeRecord, left: NodeTreeRecord, right: NodeTreeRecord, resolver?: string | undefined | null): NodeMergeExplanationRecord
  mergeExplainWithResolver(base: NodeTreeRecord, left: NodeTreeRecord, right: NodeTreeRecord, resolver: (conflict: NodeConflictRecord) => NodeResolutionRecord): NodeMergeExplanationRecord
  mergeExplainWithPolicy(base: NodeTreeRecord, left: NodeTreeRecord, right: NodeTreeRecord, policy: NativeMergePolicyRegistry): NodeMergeExplanationRecord
  mergeRange(base: NodeTreeRecord, left: NodeTreeRecord, right: NodeTreeRecord, start: Buffer, end?: Buffer | undefined | null, resolver?: string | undefined | null): NodeTreeRecord
  mergeRangeWithResolver(base: NodeTreeRecord, left: NodeTreeRecord, right: NodeTreeRecord, start: Buffer, end: Buffer | null | undefined, resolver: (conflict: NodeConflictRecord) => NodeResolutionRecord): NodeTreeRecord
  mergeRangeWithPolicy(base: NodeTreeRecord, left: NodeTreeRecord, right: NodeTreeRecord, start: Buffer, end: Buffer | undefined | null, policy: NativeMergePolicyRegistry): NodeTreeRecord
  mergePrefix(base: NodeTreeRecord, left: NodeTreeRecord, right: NodeTreeRecord, prefix: Buffer, resolver?: string | undefined | null): NodeTreeRecord
  mergePrefixWithResolver(base: NodeTreeRecord, left: NodeTreeRecord, right: NodeTreeRecord, prefix: Buffer, resolver: (conflict: NodeConflictRecord) => NodeResolutionRecord): NodeTreeRecord
  mergePrefixWithPolicy(base: NodeTreeRecord, left: NodeTreeRecord, right: NodeTreeRecord, prefix: Buffer, policy: NativeMergePolicyRegistry): NodeTreeRecord
  loadNamedRoot(name: Buffer): NodeTreeRecord | null
  loadNamedRoots(names: Array<Buffer>): NodeNamedRootSelectionRecord
  loadRetainedNamedRoots(retention: NodeNamedRootRetentionRecord): NodeNamedRootSelectionRecord
  listNamedRoots(): Array<NodeNamedRootRecord>
  listNamedRootManifests(): Array<NodeNamedRootManifestRecord>
  publishNamedRoot(name: Buffer, tree: NodeTreeRecord): void
  publishNamedRootAtMillis(name: Buffer, tree: NodeTreeRecord, timestampMillis: string): void
  deleteNamedRoot(name: Buffer): void
  compareAndSwapNamedRoot(name: Buffer, expected?: NodeTreeRecord | undefined | null, replacement?: NodeTreeRecord | undefined | null): NodeNamedRootUpdateRecord
  publishSnapshot(namespace: NodeSnapshotNamespaceRecord, id: Buffer, tree: NodeTreeRecord): void
  publishSnapshotAtMillis(namespace: NodeSnapshotNamespaceRecord, id: Buffer, tree: NodeTreeRecord, timestampMillis: string): void
  loadSnapshot(namespace: NodeSnapshotNamespaceRecord, id: Buffer): NodeTreeRecord | null
  loadSnapshots(namespace: NodeSnapshotNamespaceRecord, ids: Array<Buffer>): NodeSnapshotSelectionRecord
  listSnapshots(namespace: NodeSnapshotNamespaceRecord): Array<NodeSnapshotRecord>
  deleteSnapshot(namespace: NodeSnapshotNamespaceRecord, id: Buffer): void
  compareAndSwapSnapshot(namespace: NodeSnapshotNamespaceRecord, id: Buffer, expected?: NodeTreeRecord | undefined | null, replacement?: NodeTreeRecord | undefined | null): NodeNamedRootUpdateRecord
  compareAndSwapSnapshotAtMillis(namespace: NodeSnapshotNamespaceRecord, id: Buffer, expected: NodeTreeRecord | undefined | null, replacement: NodeTreeRecord | undefined | null, timestampMillis: string): NodeNamedRootUpdateRecord
  collectStatsJson(tree: NodeTreeRecord): string
  collectStats(tree: NodeTreeRecord): unknown
  statsDiffJson(before: NodeTreeRecord, after: NodeTreeRecord): string
  statsDiff(before: NodeTreeRecord, after: NodeTreeRecord): unknown
  debugTreeJson(tree: NodeTreeRecord): string
  debugTree(tree: NodeTreeRecord): unknown
  debugTreeText(tree: NodeTreeRecord): string
  debugCompareTreesJson(left: NodeTreeRecord, right: NodeTreeRecord): string
  debugCompareTrees(left: NodeTreeRecord, right: NodeTreeRecord): unknown
  debugCompareTreesText(left: NodeTreeRecord, right: NodeTreeRecord): string
  cacheStats(): NodeCacheStatsRecord
  clearCache(): void
  pinTreeRoot(tree: NodeTreeRecord): string
  pinTreePath(tree: NodeTreeRecord, key: Buffer): string
  unpinAllCacheNodes(): string
  metrics(): NodeMetricsRecord
  resetMetrics(): void
  publishPrefixPathHint(tree: NodeTreeRecord, prefix: Buffer): boolean
  hydratePrefixPathHint(tree: NodeTreeRecord, prefix: Buffer): boolean
  publishChangedSpansHint(base: NodeTreeRecord, changed: NodeTreeRecord, spans: Array<NodeChangedSpanRecord>): boolean
  loadChangedSpansHint(base: NodeTreeRecord, changed: NodeTreeRecord): NodeChangedSpanHintRecord | null
  structuralDiffPage(base: NodeTreeRecord, other: NodeTreeRecord, cursorJson: string | undefined | null, limit: string): NodeStructuralDiffPageRecord
  structuralDiffPageWithCursor(base: NodeTreeRecord, other: NodeTreeRecord, cursor: NodeStructuralDiffCursorRecord | undefined | null, limit: string): NodeStructuralDiffPageRecord
  markReachable(roots: Array<NodeTreeRecord>): NodeGcReachabilityRecord
  markReachableBlobs(roots: Array<NodeTreeRecord>): NodeBlobGcReachabilityRecord
  listNodeCids(): Array<Buffer>
  planGc(roots: Array<NodeTreeRecord>, candidateCids: Array<Buffer>): NodeGcPlanRecord
  sweepGc(roots: Array<NodeTreeRecord>, candidateCids: Array<Buffer>): NodeGcSweepRecord
  planStoreGc(roots: Array<NodeTreeRecord>): NodeGcPlanRecord
  sweepStoreGc(roots: Array<NodeTreeRecord>): NodeGcSweepRecord
  planStoreGcForRetention(retention: NodeNamedRootRetentionRecord): NodeGcPlanRecord
  sweepStoreGcForRetention(retention: NodeNamedRootRetentionRecord): NodeGcSweepRecord
  planBlobGc(blobStore: NativeProllyBlobStore, roots: Array<NodeTreeRecord>, candidateBlobs: Array<NodeBlobRefRecord>): NodeBlobGcPlanRecord
  sweepBlobGc(blobStore: NativeProllyBlobStore, roots: Array<NodeTreeRecord>, candidateBlobs: Array<NodeBlobRefRecord>): NodeBlobGcSweepRecord
  planBlobStoreGc(blobStore: NativeProllyBlobStore, roots: Array<NodeTreeRecord>): NodeBlobGcPlanRecord
  sweepBlobStoreGc(blobStore: NativeProllyBlobStore, roots: Array<NodeTreeRecord>): NodeBlobGcSweepRecord
  planMissingNodes(tree: NodeTreeRecord, destination: NativeProllyEngine): NodeMissingNodePlanRecord
  copyMissingNodes(tree: NodeTreeRecord, destination: NativeProllyEngine): NodeMissingNodeCopyRecord
  exportSnapshot(tree: NodeTreeRecord): NodeSnapshotBundleRecord
  importSnapshot(bundle: NodeSnapshotBundleRecord): NodeTreeRecord
}
