use super::*;

pub(crate) fn known_gc_object_kinds() -> HashSet<&'static str> {
    [
        WORKTREE_ROOT_KIND,
        TEXT_CONTENT_KIND,
        OPERATION_KIND,
        BLOB_KIND,
        MESSAGE_KIND,
        ANCHOR_KIND,
        WORKSPACE_LAYER_MANIFEST_KIND,
        WORKSPACE_LAYER_MANIFEST_PAGE_KIND,
        ARTIFACT_RESOLUTION_SNAPSHOT_KIND,
        ARTIFACT_RESOLUTION_CONTENT_KIND,
        ARTIFACT_RESOLUTION_PLAN_KIND,
        ARTIFACT_RESOLUTION_CAPTURE_KIND,
        ARTIFACT_RESOLUTION_FAILURE_KIND,
        ARTIFACT_DIRECTORY_NODE_KIND,
        ARTIFACT_FILE_NODE_KIND,
        ARTIFACT_BLOB_KIND,
        ARTIFACT_CHUNK_LIST_KIND,
        ARTIFACT_CHUNK_KIND,
        ARTIFACT_TREE_ROOT_KIND,
        ARTIFACT_ENVELOPE_KIND,
        ARTIFACT_DIVERGENCE_EVIDENCE_KIND,
    ]
    .into_iter()
    .collect()
}
